name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'docs/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Tag with GitVersion
        id: gitversion
        uses: michielvha/gitversion-tag-action@main
        with:
          configFilePath: gitversion.yml

      - name: Build and Release
        uses: michielvha/goreleaser-action@main
        with:
          github-token: ${{ github.token }}
          pgp-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
